/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import javax.swing.JButton;

/**
 *
 * @author Guillermo Velez
 */
public class Menu extends javax.swing.JFrame {
    private Modelo modeloA;
    private ControladorMenu controladormenu;
    public Menu(Modelo m){
        initComponents();
        this.setBounds(0, 0, 600,600);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        modeloA =m;
    }
    public Modelo getModeloA() {
        
        return modeloA;
    }

    public JButton getPersonaje1() {
        return Personaje1;
    }

    public JButton getPersonaje2() {
        return Personaje2;
    }

    public JButton getPersonaje3() {
        return Personaje3;
    }

    public JButton getPersonaje4() {
        return Personaje4;
    }

    public JButton getPersonaje5() {
        return Personaje5;
    }

    public ControladorMenu getControladormenu() {
        if(controladormenu==null){
            controladormenu= new ControladorMenu(this);
        }
        return controladormenu;
        
    }

    public Menu() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Personaje1 = new javax.swing.JButton();
        Personaje2 = new javax.swing.JButton();
        Personaje3 = new javax.swing.JButton();
        Personaje4 = new javax.swing.JButton();
        Personaje5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CATALOGO PERSONAJES");

        Personaje1.setText("Personaje1 ");
        Personaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Personaje1ActionPerformed(evt);
            }
        });

        Personaje2.setText("Personaje2");
        Personaje2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Personaje2ActionPerformed(evt);
            }
        });

        Personaje3.setText("Personaje3");
        Personaje3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Personaje3ActionPerformed(evt);
            }
        });

        Personaje4.setText("Personaje4");
        Personaje4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Personaje4ActionPerformed(evt);
            }
        });

        Personaje5.setText("Personaje5");
        Personaje5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Personaje5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Personaje1)
                    .addComponent(Personaje4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Personaje5)
                    .addComponent(Personaje2))
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(Personaje3)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Personaje2)
                    .addComponent(Personaje1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Personaje5)
                    .addComponent(Personaje4))
                .addGap(113, 113, 113))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Personaje3)
                .addGap(160, 160, 160))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Personaje2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Personaje2ActionPerformed
        Personaje2.addActionListener(getControladormenu());
    }//GEN-LAST:event_Personaje2ActionPerformed

    private void Personaje3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Personaje3ActionPerformed
        Personaje3.addActionListener(getControladormenu());
    }//GEN-LAST:event_Personaje3ActionPerformed

    private void Personaje4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Personaje4ActionPerformed
        Personaje4.addActionListener(getControladormenu());
    }//GEN-LAST:event_Personaje4ActionPerformed

    private void Personaje5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Personaje5ActionPerformed
        Personaje5.addActionListener(getControladormenu());
    }//GEN-LAST:event_Personaje5ActionPerformed

    private void Personaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Personaje1ActionPerformed
        Personaje1.addActionListener(getControladormenu());
        System.out.println("prueba");
    }//GEN-LAST:event_Personaje1ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Personaje1;
    private javax.swing.JButton Personaje2;
    private javax.swing.JButton Personaje3;
    private javax.swing.JButton Personaje4;
    private javax.swing.JButton Personaje5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
